version: 2.1

orbs:
  node: circleci/node@0.0.7

references:
  workspace_root: &workspace_root
                    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root
  attach_node_modules: &attach_node_modules
    steps:
      - *attach_workspace
      - run: mv /tmp/workspace/node_modules .

jobs:
  install:
    executor: node/node

    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - node_modules/

  build:
    executor: node/node

    steps:
      - checkout
      - *attach_node_modules
      - run: npm run build:production
      - persist_to_workspace:
          root: dist
          paths:
            - dist

  documentation:
    executor: node/node

    steps:
      - checkout
      - *attach_node_modules
      - run: mv
      - run: npm run docs

  deploy:
    executor: node/node

    steps:
      - checkout
      - *attach_node_modules
      - run:
          name: Deploy
          command: bash tools/deploy.sh

workflows:
  version: 2
  main:
    jobs:
      - install

      - build:
          requires:
            - install

      - documentation:
          requires:
            - install
          filters:
            branches:
              only: master

      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/