version: 2.1

orbs:
  node: circleci/node@0.0.7
  github-release: h-matsuo/github-release@0.1.3

references:
  workspace_root: &workspace_root
                    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root
  copy_node_modules: &copy_node_modules
    run: mv /tmp/workspace/node_modules .

jobs:
  install:
    executor: node/node

    steps:
      - *attach_workspace
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: mv node_modules/ /tmp/workspace/
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - node_modules/

  build:
    executor: node/node

    steps:
      - checkout
      - *attach_workspace
      - *copy_node_modules
      - run: npm run build:production
      - run: mv dist/ /tmp/workspace/
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - dist/

  documentation:
    executor: node/node

    steps:
      - checkout
      - *attach_workspace
      - *copy_node_modules
      - run: npm run docs -- --gaID $GA_ID
      - run:
          name: Committing Documentation
          command: |
            rev=$(git rev-parse --short HEAD)

            git config credential.helper "cache --timeout=120"
            git config user.email "$GH_EMAIL"
            git config user.name "$GH_USERNAME"

            git remote add upstream "https://$GITHUB_TOKEN@github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git"
            git checkout -b upstream/gh-pages
            git pull upstream gh-pages

            git add --force docs
            git commit --message "chore: deploy ${rev}"
            git push --quiet upstream HEAD:gh-pages > /dev/null 2>&1

  deploy:
    executor: node/node

    steps:
      - checkout
      - *attach_workspace
      - *copy_node_modules
      - run: mv /tmp/workspace/dist .
      - run:
          name: Deploy
          command: bash tools/deploy.sh
      - github-release/create:
          tag: $CIRCLE_TAG
          title: Version $CIRCLE_TAG
          description: I have no idea what to put here...
          file-path: build/

workflows:
  version: 2
  main:
    jobs:
      - install

      - build:
          requires:
            - install

      - documentation:
          requires:
            - install
      #          filters:
      #            branches:
      #              only: master

      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/