version: 2.1

orbs:
  node: circleci/node@0.0.7

jobs:
  install:
    executor: node/node

    steps:
      - checkout
      - node/install-package-manager:
          npm: true
      - run: npm install --unsafe-perm
      - persist_to_workspace:
          root: node_modules
          paths:
            - node_modules

  build:
    executor: node/node

    steps:
      - checkout
      - attach_workspace:
          at: node_modules
      - run: npm run build:production
      - persist_to_workspace:
          root: dist
          paths:
            - dist

  documentation:
    executor: node/node

    steps:
      - checkout
      - attach_workspace:
          at: node_modules
      - run: npm run docs

  deploy:
    executor: node/node

    steps:
      - checkout
      - attach_workspace:
          at: node_modules
      - run:
          name: Deploy
          command: bash tools/deploy.sh

workflows:
  version: 2
  main:
    jobs:
      - install

      - build:
          requires:
            - install

      - documentation:
          requires:
            - install
          filters:
            branches:
              only: master

      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/